name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v4

      - name: Configurer CMake
        run: cmake -B build

      - name: Compiler
        run: cmake --build build --config Release