name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Prepare artifact
        shell: bash
        run: |
          mkdir release
          
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp build/Release/OBJtoNDS.exe release/
          else
            cp build/OBJtoNDS release/
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OBJtoNDS-${{ matrix.name }}
          path: release/


  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/*