name: Build release executables

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            c_compiler: gcc
            cpp_compiler: g++

          - os: windows-latest
            name: windows
            c_compiler: cl
            cpp_compiler: cl

          - os: macos-latest
            name: macos
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get version
        id: version
        shell: bash
        run: echo "version=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake
          -B build
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=Release
          -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Prepare executable (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir release
          cp build/OBJtoNDS release/OBJtoNDS-${{ steps.version.outputs.version }}-${{ matrix.name }}

      - name: Prepare executable (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir release
          cp build/Release/OBJtoNDS.exe release/OBJtoNDS-${{ steps.version.outputs.version }}-${{ matrix.name }}.exe

      - name: Upload executable
        uses: actions/upload-artifact@v5
        with:
          name: OBJtoNDS-${{ matrix.name }}
          path: release/*